# New ports collection makefile for:	login-manager
# Date created:				2012-10-26
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	login-manager
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Login manager

RUN_DEPENDS=	ark-gui-fonts>=0:${PORTSDIR}/arkports/gui-fonts \
		ark-slim-conf>=0:${PORTSDIR}/arkports/slim-conf \
		slim>=0:${PORTSDIR}/x11/slim

NO_WRKSUBDIR=	yes
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
