#!/bin/sh

if [ "$2" != 'DO-INSTALL' ]; then
    exit
fi

# command
CAT="cat"
ECHO="echo"

# setting file
PORTMASTER_CONF_SETTING="files/portmaster_setting"

# append header and footer
CONF_HEADER="# Begin of $1 settings"
CONF_FOOTER="# End of $1 settings"

# install command
${ECHO} ${CONF_HEADER} >> ${PKG_PREFIX}/etc/portmaster.rc
${CAT} ${PORTMASTER_CONF_SETTING} >> ${PKG_PREFIX}/etc/portmaster.rc
${ECHO} ${CONF_FOOTER} >> ${PKG_PREFIX}/etc/portmaster.rc
