# New ports collection makefile for:	screen-lock
# Date created:				2013-03-16
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	screen-lock
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Screen lock

RUN_DEPENDS=	xtrlock>=0:${PORTSDIR}/x11/xtrlock

NO_WRKSUBDIR=	yes
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
