# New ports collection makefile for:	console-vim
# Date created:				2013-02-17
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	console-editor
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Console editor

RUN_DEPENDS=	ark-vim-conf>=0:${PORTSDIR}/arkports/vim-conf \
		vim>=0:${PORTSDIR}/editors/vim

NO_WRKSUBDIR=	yes
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
