# New ports collection makefile for:	usb-mounter
# Date created:				2013-01-31
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	usb-mounter
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Usb auto mounter

RUN_DEPENDS=	ark-volman-conf>=0:${PORTSDIR}/arkports/volman-conf \
		ark-volman>=0:${PORTSDIR}/arkports/volman

NO_WRKSUBDIR=	yes
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
