# New ports collection makefile for:	terminal
# Date created:				2012-10-16
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	terminal
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Virtual terminal

RUN_DEPENDS=	ark-xterm-conf>=0:${PORTSDIR}/arkports/xterm-conf \
		xterm>=0:${PORTSDIR}/x11/xterm

NO_WRKSUBDIR=	yes
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
