#!/bin/sh

if [ "$2" != 'DO-INSTALL' ]; then
    exit
fi

# command
CAT="cat"
ECHO="echo"

# setting file
LOADER_SETTING="files/loader_setting"

# append header and footer
CONF_HEADER="# Begin of $1 settings"
CONF_FOOTER="# End of $1 settings"

# install command
${ECHO} ${CONF_HEADER} >> /boot/loader.conf
${CAT} ${LOADER_SETTING} >> /boot/loader.conf
${ECHO} ${CONF_FOOTER} >> /boot/loader.conf
