# New ports collection makefile for:	window-panel
# Date created:				2012-10-06
# Whom:					Dachi Chang <femc7488@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	window-panel
PORTVERSION=	1.0
CATEGORIES=	arkports
MASTER_SITES=	# none
DISTFILES=	# none

MAINTAINER=	femc7488@gmail.com
COMMENT=	Window panel

RUN_DEPENDS=	ark-tint2-conf>=0:${PORTSDIR}/arkports/tint2-conf \
		tint2>=0:${PORTSDIR}/x11/tint

NO_WRKSUBDIR=	yes
NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
