#!/bin/sh

if [ "$2" != 'DO-INSTALL' ]; then
    exit
fi

# command
CAT="cat"
ECHO="echo"
PRINTF="printf"
MOUNT="mount -a"
MKDIR="mkdir -p"

# setting file
MAKE_SETTING="files/make_setting"

# append header and footer
CONF_HEADER="# Begin of $1 settings"
CONF_FOOTER="# End of $1 settings"

# install command
${ECHO} ${CONF_HEADER} >> /etc/make.conf
xorg_drivers=""
new_xorg_flag="on"
kms_flag=""
# check all need driver
for driver in "$@"; do
    case "$driver" in
    "new_intel")
        xorg_drivers="new_intel $xorg_drivers"
        ;;
    "old_intel")
        xorg_drivers="old_intel $xorg_drivers"
        ;;
    "nvidia")
        xorg_drivers="nvidia $xorg_drivers"
        ;;
    esac
done
#check intel driver
for intel_driver in $xorg_drivers; do
    case "$intel_driver" in
    "new_intel")
        kms_flag="on"
        ;;
    "old_intel")
        new_xorg_flag="off"
        kms_flag="off"
        ;;
    esac
done
#setting xorg video driver config
if [ "$new_xorg_flag" == "on" ]; then
    ${ECHO} "WITH_NEW_XORG=yes" >> /etc/make.conf
fi
if [ "$kms_flag" == "on" ]; then
    ${ECHO} "WITH_KMS=yes" >> /etc/make.conf
fi
if [ "$xorg_drivers" != "" ]; then
    ${ECHO} "XORG_VIDEO_DRIVER=$xorg_drivers" >> /etc/make.conf
fi
#setting window base config
${CAT} ${MAKE_SETTING} >> /etc/make.conf
${ECHO} ${CONF_FOOTER} >> /etc/make.conf
